# Generated by Django 5.0.4 on 2024-04-24 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('data_inicio', models.DateField(verbose_name='data de inicio')),
                ('data_fim', models.DateField(verbose_name='data de encerramento')),
                ('regras', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('instrutor', 'INSTRUTOR'), ('rececionista', 'RECECIONISTA'), ('gerente', 'GERENTE'), ('pt', 'PT'), ('limpeza', 'LIMPEZA'), ('nutricionista', 'NUTRICIONISTA')], max_length=20)),
                ('horario_trabalho', models.DateTimeField(verbose_name='horario de trabalho')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.TextField(blank=True, null=True)),
                ('horarios_treino', models.CharField(blank=True, max_length=200, null=True)),
                ('progresso_fitness', models.TextField()),
                ('conquistas', models.TextField()),
                ('stats_treino', models.TextField()),
                ('desafios', models.ManyToManyField(related_name='desafios', to='fitness.desafio')),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('horario', models.DateTimeField(verbose_name='horario de aula')),
                ('max_participantes', models.IntegerField(default=0)),
                ('participantes', models.ManyToManyField(related_name='participantes', to='fitness.cliente')),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('user_type', models.CharField(choices=[('cliente', 'CLIENTE'), ('funcionario', 'FUNCIONARIO')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=200)),
                ('pub_data', models.DateTimeField(verbose_name='data de publicacao')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.utilizador')),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fitness.utilizador'),
        ),
        migrations.AddField(
            model_name='desafio',
            name='participantes',
            field=models.ManyToManyField(related_name='participantes', to='fitness.utilizador'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('pub_data', models.DateTimeField(verbose_name='data de publicacao')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.utilizador')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fitness.utilizador'),
        ),
    ]
