# Generated by Django 5.0.4 on 2024-05-06 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fitness.post'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='conquistas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='progresso_fitness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='stats_treino',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='horario_trabalho',
            field=models.DateTimeField(blank=True, null=True, verbose_name='horario de trabalho'),
        ),
    ]
