# Generated by Django 5.0.4 on 2024-05-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_comentario_post_alter_cliente_conquistas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='user',
            new_name='utilizador',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='user',
            new_name='utilizador',
        ),
    ]
