# Generated by Django 5.0.4 on 2024-05-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_rename_user_cliente_utilizador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='conquistas',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='desafios',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='stats_treino',
        ),
        migrations.AlterField(
            model_name='desafio',
            name='participantes',
            field=models.ManyToManyField(related_name='desafio', to='fitness.utilizador'),
        ),
    ]
