# Generated by Django 5.0.4 on 2024-05-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_remove_cliente_conquistas_remove_cliente_desafios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='participantes',
            field=models.ManyToManyField(related_name='desafios', to='fitness.utilizador'),
        ),
    ]
