# Generated by Django 5.0.4 on 2024-05-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_alter_desafio_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='participantes',
            field=models.ManyToManyField(related_name='aulas', to='fitness.cliente'),
        ),
    ]
