# Generated by Django 5.0.4 on 2024-05-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_alter_aula_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='meta',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='progresso_fitness',
            field=models.TextField(blank=True, default=''),
        ),
    ]
