# Generated by Django 5.0.4 on 2024-05-09 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_alter_cliente_meta_alter_cliente_progresso_fitness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.post'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(default=''),
        ),
    ]
