# Generated by Django 5.0.4 on 2024-05-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_alter_comentario_post_alter_comentario_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='assunto',
        ),
        migrations.AddField(
            model_name='post',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
