# Generated by Django 5.0.4 on 2024-05-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_remove_post_assunto_post_descricao_post_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='meta',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
