# Generated by Django 5.0.4 on 2024-05-09 21:11

import fitness.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_alter_cliente_meta_alter_post_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_pfp.jpg', upload_to='profile_pictures/'),
        ),
    ]
